{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "1d5b53f3",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Loading the data... Please wait.\n",
      "Your input dataset\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Age</th>\n",
       "      <th>Gender</th>\n",
       "      <th>BMI</th>\n",
       "      <th>Antibody_batch</th>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Pseudo</th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>ID1</th>\n",
       "      <td>22.0</td>\n",
       "      <td>1.0</td>\n",
       "      <td>18.8</td>\n",
       "      <td>SF29990791</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>ID2</th>\n",
       "      <td>65.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>29.5</td>\n",
       "      <td>SF29990793</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>ID3</th>\n",
       "      <td>46.0</td>\n",
       "      <td>1.0</td>\n",
       "      <td>25.8</td>\n",
       "      <td>100574320</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>ID4</th>\n",
       "      <td>49.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>23.9</td>\n",
       "      <td>SF29990791</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>ID5</th>\n",
       "      <td>33.0</td>\n",
       "      <td>1.0</td>\n",
       "      <td>23.1</td>\n",
       "      <td>SF29990823</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>ID1438</th>\n",
       "      <td>42.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>23.5</td>\n",
       "      <td>100574320</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>ID1439</th>\n",
       "      <td>39.0</td>\n",
       "      <td>1.0</td>\n",
       "      <td>22.3</td>\n",
       "      <td>SF29990823</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>ID1440</th>\n",
       "      <td>65.0</td>\n",
       "      <td>1.0</td>\n",
       "      <td>22.7</td>\n",
       "      <td>SF29990822</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>ID1441</th>\n",
       "      <td>45.0</td>\n",
       "      <td>1.0</td>\n",
       "      <td>22.9</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>ID1442</th>\n",
       "      <td>38.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>22.9</td>\n",
       "      <td>SF29990806</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>1442 rows × 4 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "         Age  Gender   BMI Antibody_batch\n",
       "Pseudo                                   \n",
       "ID1     22.0     1.0  18.8     SF29990791\n",
       "ID2     65.0     0.0  29.5     SF29990793\n",
       "ID3     46.0     1.0  25.8      100574320\n",
       "ID4     49.0     0.0  23.9     SF29990791\n",
       "ID5     33.0     1.0  23.1     SF29990823\n",
       "...      ...     ...   ...            ...\n",
       "ID1438  42.0     0.0  23.5      100574320\n",
       "ID1439  39.0     1.0  22.3     SF29990823\n",
       "ID1440  65.0     1.0  22.7     SF29990822\n",
       "ID1441  45.0     1.0  22.9            NaN\n",
       "ID1442  38.0     0.0  22.9     SF29990806\n",
       "\n",
       "[1442 rows x 4 columns]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Please provide the exact target columnname.Your input:bmi\n",
      "Column name cannot be found. Please make sure to exactly copy and past the target column name.\n",
      "Your input dataset\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Age</th>\n",
       "      <th>Gender</th>\n",
       "      <th>BMI</th>\n",
       "      <th>Antibody_batch</th>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Pseudo</th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>ID1</th>\n",
       "      <td>22.0</td>\n",
       "      <td>1.0</td>\n",
       "      <td>18.8</td>\n",
       "      <td>SF29990791</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>ID2</th>\n",
       "      <td>65.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>29.5</td>\n",
       "      <td>SF29990793</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>ID3</th>\n",
       "      <td>46.0</td>\n",
       "      <td>1.0</td>\n",
       "      <td>25.8</td>\n",
       "      <td>100574320</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>ID4</th>\n",
       "      <td>49.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>23.9</td>\n",
       "      <td>SF29990791</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>ID5</th>\n",
       "      <td>33.0</td>\n",
       "      <td>1.0</td>\n",
       "      <td>23.1</td>\n",
       "      <td>SF29990823</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>ID1438</th>\n",
       "      <td>42.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>23.5</td>\n",
       "      <td>100574320</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>ID1439</th>\n",
       "      <td>39.0</td>\n",
       "      <td>1.0</td>\n",
       "      <td>22.3</td>\n",
       "      <td>SF29990823</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>ID1440</th>\n",
       "      <td>65.0</td>\n",
       "      <td>1.0</td>\n",
       "      <td>22.7</td>\n",
       "      <td>SF29990822</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>ID1441</th>\n",
       "      <td>45.0</td>\n",
       "      <td>1.0</td>\n",
       "      <td>22.9</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>ID1442</th>\n",
       "      <td>38.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>22.9</td>\n",
       "      <td>SF29990806</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>1442 rows × 4 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "         Age  Gender   BMI Antibody_batch\n",
       "Pseudo                                   \n",
       "ID1     22.0     1.0  18.8     SF29990791\n",
       "ID2     65.0     0.0  29.5     SF29990793\n",
       "ID3     46.0     1.0  25.8      100574320\n",
       "ID4     49.0     0.0  23.9     SF29990791\n",
       "ID5     33.0     1.0  23.1     SF29990823\n",
       "...      ...     ...   ...            ...\n",
       "ID1438  42.0     0.0  23.5      100574320\n",
       "ID1439  39.0     1.0  22.3     SF29990823\n",
       "ID1440  65.0     1.0  22.7     SF29990822\n",
       "ID1441  45.0     1.0  22.9            NaN\n",
       "ID1442  38.0     0.0  22.9     SF29990806\n",
       "\n",
       "[1442 rows x 4 columns]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Please provide the exact target columnname.Your input:bmi\n",
      "Column name cannot be found. Please make sure to exactly copy and past the target column name.\n",
      "Your input dataset\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Age</th>\n",
       "      <th>Gender</th>\n",
       "      <th>BMI</th>\n",
       "      <th>Antibody_batch</th>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Pseudo</th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>ID1</th>\n",
       "      <td>22.0</td>\n",
       "      <td>1.0</td>\n",
       "      <td>18.8</td>\n",
       "      <td>SF29990791</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>ID2</th>\n",
       "      <td>65.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>29.5</td>\n",
       "      <td>SF29990793</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>ID3</th>\n",
       "      <td>46.0</td>\n",
       "      <td>1.0</td>\n",
       "      <td>25.8</td>\n",
       "      <td>100574320</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>ID4</th>\n",
       "      <td>49.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>23.9</td>\n",
       "      <td>SF29990791</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>ID5</th>\n",
       "      <td>33.0</td>\n",
       "      <td>1.0</td>\n",
       "      <td>23.1</td>\n",
       "      <td>SF29990823</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>ID1438</th>\n",
       "      <td>42.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>23.5</td>\n",
       "      <td>100574320</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>ID1439</th>\n",
       "      <td>39.0</td>\n",
       "      <td>1.0</td>\n",
       "      <td>22.3</td>\n",
       "      <td>SF29990823</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>ID1440</th>\n",
       "      <td>65.0</td>\n",
       "      <td>1.0</td>\n",
       "      <td>22.7</td>\n",
       "      <td>SF29990822</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>ID1441</th>\n",
       "      <td>45.0</td>\n",
       "      <td>1.0</td>\n",
       "      <td>22.9</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>ID1442</th>\n",
       "      <td>38.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>22.9</td>\n",
       "      <td>SF29990806</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>1442 rows × 4 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "         Age  Gender   BMI Antibody_batch\n",
       "Pseudo                                   \n",
       "ID1     22.0     1.0  18.8     SF29990791\n",
       "ID2     65.0     0.0  29.5     SF29990793\n",
       "ID3     46.0     1.0  25.8      100574320\n",
       "ID4     49.0     0.0  23.9     SF29990791\n",
       "ID5     33.0     1.0  23.1     SF29990823\n",
       "...      ...     ...   ...            ...\n",
       "ID1438  42.0     0.0  23.5      100574320\n",
       "ID1439  39.0     1.0  22.3     SF29990823\n",
       "ID1440  65.0     1.0  22.7     SF29990822\n",
       "ID1441  45.0     1.0  22.9            NaN\n",
       "ID1442  38.0     0.0  22.9     SF29990806\n",
       "\n",
       "[1442 rows x 4 columns]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Please provide the exact target columnname.Your input:BMI\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>BMI</th>\n",
       "      <th>Age</th>\n",
       "      <th>Gender</th>\n",
       "      <th>Antibody_batch</th>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Pseudo</th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>ID1</th>\n",
       "      <td>18.8</td>\n",
       "      <td>22.0</td>\n",
       "      <td>1.0</td>\n",
       "      <td>SF29990791</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>ID2</th>\n",
       "      <td>29.5</td>\n",
       "      <td>65.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>SF29990793</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>ID3</th>\n",
       "      <td>25.8</td>\n",
       "      <td>46.0</td>\n",
       "      <td>1.0</td>\n",
       "      <td>100574320</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>ID4</th>\n",
       "      <td>23.9</td>\n",
       "      <td>49.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>SF29990791</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>ID5</th>\n",
       "      <td>23.1</td>\n",
       "      <td>33.0</td>\n",
       "      <td>1.0</td>\n",
       "      <td>SF29990823</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>ID1438</th>\n",
       "      <td>23.5</td>\n",
       "      <td>42.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>100574320</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>ID1439</th>\n",
       "      <td>22.3</td>\n",
       "      <td>39.0</td>\n",
       "      <td>1.0</td>\n",
       "      <td>SF29990823</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>ID1440</th>\n",
       "      <td>22.7</td>\n",
       "      <td>65.0</td>\n",
       "      <td>1.0</td>\n",
       "      <td>SF29990822</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>ID1441</th>\n",
       "      <td>22.9</td>\n",
       "      <td>45.0</td>\n",
       "      <td>1.0</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>ID1442</th>\n",
       "      <td>22.9</td>\n",
       "      <td>38.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>SF29990806</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>1442 rows × 4 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "         BMI   Age  Gender Antibody_batch\n",
       "Pseudo                                   \n",
       "ID1     18.8  22.0     1.0     SF29990791\n",
       "ID2     29.5  65.0     0.0     SF29990793\n",
       "ID3     25.8  46.0     1.0      100574320\n",
       "ID4     23.9  49.0     0.0     SF29990791\n",
       "ID5     23.1  33.0     1.0     SF29990823\n",
       "...      ...   ...     ...            ...\n",
       "ID1438  23.5  42.0     0.0      100574320\n",
       "ID1439  22.3  39.0     1.0     SF29990823\n",
       "ID1440  22.7  65.0     1.0     SF29990822\n",
       "ID1441  22.9  45.0     1.0            NaN\n",
       "ID1442  22.9  38.0     0.0     SF29990806\n",
       "\n",
       "[1442 rows x 4 columns]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "#### Description ####\n",
      "The first column of the preprocessed dataset is supposed to be your selected target column. The remaining columns should be the remaining columns as predictors.\n",
      "Is this dataset correctly sorted?\n",
      "Type y for Yes\n",
      "Type n for No\n",
      "Your input:n\n",
      "Dataset is not correctly sorted.\n",
      "Do you want to terminate the program or start over?\n",
      "Type \"t\" to terminate\n",
      "Type \"s\" to start over\n",
      "s\n",
      "Your input dataset\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>BMI</th>\n",
       "      <th>Age</th>\n",
       "      <th>Gender</th>\n",
       "      <th>Antibody_batch</th>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Pseudo</th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>ID1</th>\n",
       "      <td>18.8</td>\n",
       "      <td>22.0</td>\n",
       "      <td>1.0</td>\n",
       "      <td>SF29990791</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>ID2</th>\n",
       "      <td>29.5</td>\n",
       "      <td>65.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>SF29990793</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>ID3</th>\n",
       "      <td>25.8</td>\n",
       "      <td>46.0</td>\n",
       "      <td>1.0</td>\n",
       "      <td>100574320</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>ID4</th>\n",
       "      <td>23.9</td>\n",
       "      <td>49.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>SF29990791</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>ID5</th>\n",
       "      <td>23.1</td>\n",
       "      <td>33.0</td>\n",
       "      <td>1.0</td>\n",
       "      <td>SF29990823</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>ID1438</th>\n",
       "      <td>23.5</td>\n",
       "      <td>42.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>100574320</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>ID1439</th>\n",
       "      <td>22.3</td>\n",
       "      <td>39.0</td>\n",
       "      <td>1.0</td>\n",
       "      <td>SF29990823</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>ID1440</th>\n",
       "      <td>22.7</td>\n",
       "      <td>65.0</td>\n",
       "      <td>1.0</td>\n",
       "      <td>SF29990822</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>ID1441</th>\n",
       "      <td>22.9</td>\n",
       "      <td>45.0</td>\n",
       "      <td>1.0</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>ID1442</th>\n",
       "      <td>22.9</td>\n",
       "      <td>38.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>SF29990806</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>1442 rows × 4 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "         BMI   Age  Gender Antibody_batch\n",
       "Pseudo                                   \n",
       "ID1     18.8  22.0     1.0     SF29990791\n",
       "ID2     29.5  65.0     0.0     SF29990793\n",
       "ID3     25.8  46.0     1.0      100574320\n",
       "ID4     23.9  49.0     0.0     SF29990791\n",
       "ID5     23.1  33.0     1.0     SF29990823\n",
       "...      ...   ...     ...            ...\n",
       "ID1438  23.5  42.0     0.0      100574320\n",
       "ID1439  22.3  39.0     1.0     SF29990823\n",
       "ID1440  22.7  65.0     1.0     SF29990822\n",
       "ID1441  22.9  45.0     1.0            NaN\n",
       "ID1442  22.9  38.0     0.0     SF29990806\n",
       "\n",
       "[1442 rows x 4 columns]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "import pandas as pd\n",
    "import sys\n",
    "\n",
    "class Preprocessing():\n",
    "    \"A class to sort the dataset with the first column as target and the remaining as features\"\n",
    "    def __init__(self, dataset):\n",
    "        self.dataset = dataset\n",
    "    \n",
    "    def sort_dataset(self):\n",
    "        \"Requests the target and features from the user and places the target as the first column\"\n",
    "        \"and checks whether the sorted dataset is correct\"\n",
    "        while True:\n",
    "            self.dataset = pd.DataFrame(self.dataset)\n",
    "            print(\"Your input dataset\")\n",
    "            display(self.dataset)\n",
    "            request_target = str(input(\"Please provide the exact target columnname.Your input:\"))\n",
    "        \n",
    "            try:\n",
    "                first_column = self.dataset.pop(request_target)\n",
    "                self.dataset.insert(0, request_target, first_column)\n",
    "                display(self.dataset)\n",
    "            except:\n",
    "                print(\"Column name cannot be found. Please make sure to exactly copy and past the target column name.\")\n",
    "                continue \n",
    "                \n",
    "            try:   \n",
    "                check_dataset = input(\"#### Description ####\\nThe first column of the preprocessed dataset is supposed to be your selected target column. The remaining columns should be the remaining columns as predictors.\\nIs this dataset correctly sorted?\\nType y for Yes\\nType n for No\\nYour input:\")\n",
    "            except:\n",
    "                print(\"Please only type \\\"y\\\" for Yes or \\\"n\\\" for No\")\n",
    "            \n",
    "\n",
    "            if check_dataset == \"y\":\n",
    "                print(\"Your input: Dataset is correctly sorted and stored.\")\n",
    "                target = self.dataset.iloc[:, 0]    # Splits the dataset into the target column\n",
    "                features = self.dataset.iloc[: , 1:] # Splits the dataset into the features column(s)\n",
    "                return target, features\n",
    "                \n",
    "            if check_dataset == \"n\":\n",
    "                print(\"Dataset is not correctly sorted.\")\n",
    "                try:\n",
    "                    check_terminate = str(input(\"Do you want to terminate the program or start over?\\nType \\\"t\\\" to terminate\\nType \\\"s\\\" to start over\\n\"))\n",
    "                except:\n",
    "                    print(\"Please only type \\\"t\\\" to terminate the program or \\\"r\\\" to restart\")\n",
    "                    if check_terminate == \"t\":\n",
    "                        quit()\n",
    "                    if check_terminate == \"r\":\n",
    "                        continue \n",
    "                        \n",
    "print(\"Loading the data... Please wait.\")    \n",
    "df = pd.read_csv('Covariates.csv', index_col=0, sep=\"\\t\")\n",
    "target, features = Preprocessing(df).sort_dataset()\n",
    "\n",
    "\n",
    "#MetaPhlan3 "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d0fba618",
   "metadata": {},
   "outputs": [],
   "source": [
    "i"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
